const tableData = [
    
     {
       Sr_No: "29",
        Application_ID: "A190821013",
        Borrower_Name: "HARVENDRA CHAUHAN",
        Contact_No.: "9811561311",
        Current_Lender: "SMFG",
        CuPresent_By: "AXIS",
        NACH-NON-NACH: "NON NACH",
        NACH_Status: "Rejected",
        Reason Description: "-",
        UMRN: "-",
        EMI DATE: "1/5/24",
        INSTITUTE NAME: "Ansal university",
        Course Name: "BSC CLINICAL PSYCHOLOGY",
        Stage: "Repayment",
        EMI_Amount: "1967"
      },
      {
       Sr_No: "30",
        Application_ID: "A190910032",
        Borrower_Name: "Poornima Prashar",
        Contact_No.: "7741940087",
        Current_Lender: "SMFG",
        CuPresent_By: "DIGIO SMFG",
        NACH-NON-NACH: "NACH",
        NACH_Status: "Registered",
        Reason Description: "-",
        UMRN: "ORBC0000000003254834",
        EMI DATE: "1/5/24",
        INSTITUTE NAME: "uclan",
        Course Name: "Bachelor of Arts with Honours in Sports Journalism",
        Stage: "Repayment",
        EMI_Amount: "6375"
      },
      {
       Sr_No: "31",
        Application_ID: "A190913033",
        Borrower_Name: "Aditya Kumar",
        Contact_No.: "7890009847",
        Current_Lender: "Eduvanz Financing Pvt. Ltd.",
        CuPresent_By: "AXIS",
        NACH-NON-NACH: "NACH",
        NACH_Status: "Registered",
        Reason Description: "-",
        UMRN: "MAHB0000000003725465",
        EMI DATE: "1/5/24",
        INSTITUTE NAME: "TSW",
        Course Name: "PGCFBM",
        Stage: "Repayment",
        EMI_Amount: "13251"
      },
      {
       Sr_No: "32",
        Application_ID: "A190924115",
        Borrower_Name: "utkarsh Upendra",
        Contact_No.: "9090162259",
        Current_Lender: "Eduvanz Financing Pvt. Ltd.",
        CuPresent_By: "AXIS",
        NACH-NON-NACH: "NACH",
        NACH_Status: "Registered",
        Reason Description: "-",
        UMRN: "KKBK7000000003335200",
        EMI DATE: "1/5/24",
        INSTITUTE NAME: "IBS",
        Course Name: "IBS MBA",
        Stage: "Repayment",
        EMI_Amount: "3570"
      },
      {
       Sr_No: "33",
        Application_ID: "A190924147",
        Borrower_Name: "Chintala Raju",
        Contact_No.: "9849266363",
        Current_Lender: "Eduvanz Financing Pvt. Ltd.",
        CuPresent_By: "AXIS",
        NACH-NON-NACH: "NACH",
        NACH_Status: "Registered",
        Reason Description: "-",
        UMRN: "UTIB7000000008802413",
        EMI DATE: "1/5/24",
        INSTITUTE NAME: "Indian school of science and management",
        Course Name: "master of business administration  from issm",
        Stage: "Repayment",
        EMI_Amount: "6251"
      },
      {
       Sr_No: "34",
        Application_ID: "A190930114",
        Borrower_Name: "Ravi Arora",
        Contact_No.: "9559015199",
        Current_Lender: "Eduvanz Financing Pvt. Ltd.",
        CuPresent_By: "AXIS",
        NACH-NON-NACH: "NACH",
        NACH_Status: "Registered",
        Reason Description: "-",
        UMRN: "BARB0000000008250379",
        EMI DATE: "1/5/24",
        INSTITUTE NAME: "IBS",
        Course Name: "IBS MBA",
        Stage: "Repayment",
        EMI_Amount: "2405"
      },
      {
       Sr_No: "35",
        Application_ID: "A191002015",
        Borrower_Name: "harsheel vora",
        Contact_No.: "9619555235",
        Current_Lender: "Eduvanz Financing Pvt. Ltd.",
        CuPresent_By: "AXIS",
        NACH-NON-NACH: "NACH",
        NACH_Status: "Registered",
        Reason Description: "-",
        UMRN: "HDFC0000000009306070",
        EMI DATE: "1/5/24",
        INSTITUTE NAME: "IBS",
        Course Name: "IBS MBA",
        Stage: "Repayment",
        EMI_Amount: "8452"
      },
      {
       Sr_No: "36",
        Application_ID: "A191004117",
        Borrower_Name: "Shinu Sinha",
        Contact_No.: "9839843373",
        Current_Lender: "SMFG",
        CuPresent_By: "AXIS",
        NACH-NON-NACH: "NACH",
        NACH_Status: "Registered",
        Reason Description: "-",
        UMRN: "UBIN0000000005157784",
        EMI DATE: "1/5/24",
        INSTITUTE NAME: "IBS",
        Course Name: "IBS MBA",
        Stage: "Repayment",
        EMI_Amount: "3571"
      },
      {
       Sr_No: "37",
        Application_ID: "A191005083",
        Borrower_Name: "Bhavesh Vahane",
        Contact_No.: "9021099790",
        Current_Lender: "SMFG",
        CuPresent_By: "RAZORPAY EDUVANZ",
        NACH-NON-NACH: "NACH",
        NACH_Status: "Registered",
        Reason Description: "-",
        UMRN: "token_JfH2HlOxRX7MR0",
        EMI DATE: "1/5/24",
        INSTITUTE NAME: "Seed Infotech",
        Course Name: "IT-ERP SAP Training",
        Stage: "Repayment",
        EMI_Amount: "8752"
      },
      {
       Sr_No: "38",
        Application_ID: "A191006022",
        Borrower_Name: "Padamraj Chopra",
        Contact_No.: "8108294706",
        Current_Lender: "SMFG",
        CuPresent_By: "DIGIO SMFG",
        NACH-NON-NACH: "NACH",
        NACH_Status: "Registered",
        Reason Description: "-",
        UMRN: "BKID0000000007795069",
        EMI DATE: "1/5/24",
        INSTITUTE NAME: "IBS",
        Course Name: "IBS MBA",
        Stage: "Repayment",
        EMI_Amount: "8452"
      },
      {
       Sr_No: "39",
        Application_ID: "A191007015",
        Borrower_Name: "Ramesh gupta",
        Contact_No.: "9999375133",
        Current_Lender: "SMFG",
        CuPresent_By: "DIGIO SMFG",
        NACH-NON-NACH: "NACH",
        NACH_Status: "Registered",
        Reason Description: "-",
        UMRN: "HDFC0000000009371722",
        EMI DATE: "1/5/24",
        INSTITUTE NAME: "IBS",
        Course Name: "IBS MBA",
        Stage: "Repayment",
        EMI_Amount: "3481"
      },
      {
       Sr_No: "40",
        Application_ID: "A191007019",
        Borrower_Name: "JAMES MATHEW",
        Contact_No.: "6200205971",
        Current_Lender: "SMFG",
        CuPresent_By: "DIGIO SMFG",
        NACH-NON-NACH: "NACH",
        NACH_Status: "Registered",
        Reason Description: "-",
        UMRN: "FDRL0000000002085602",
        EMI DATE: "1/5/24",
        INSTITUTE NAME: "IBS",
        Course Name: "IBS MBA",
        Stage: "Repayment",
        EMI_Amount: "3540"
      },
      {
       Sr_No: "41",
        Application_ID: "A191007020",
        Borrower_Name: "Abhishek Babbar",
        Contact_No.: "9565812566",
        Current_Lender: "SMFG",
        CuPresent_By: "RAZORPAY EDUVANZ",
        NACH-NON-NACH: "NACH",
        NACH_Status: "Registered",
        Reason Description: "-",
        UMRN: "token_HAFxnyUTca0dIn",
        EMI DATE: "1/5/24",
        INSTITUTE NAME: "IBS",
        Course Name: "IBS MBA",
        Stage: "Repayment",
        EMI_Amount: "3601"
      },
      {
       Sr_No: "42",
        Application_ID: "A191007061",
        Borrower_Name: "aanchal chanana",
        Contact_No.: "9999636037",
        Current_Lender: "SMFG",
        CuPresent_By: "DIGIO SMFG",
        NACH-NON-NACH: "NACH",
        NACH_Status: "Registered",
        Reason Description: "-",
        UMRN: "HDFC7000000010554394",
        EMI DATE: "1/5/24",
        INSTITUTE NAME: "IBS",
        Course Name: "IBS MBA",
        Stage: "Repayment",
        EMI_Amount: "3481"
      },
      {
       Sr_No: "43",
        Application_ID: "A191009094",
        Borrower_Name: "BRAJESH RUIA",
        Contact_No.: "9820739447",
        Current_Lender: "SMFG",
        CuPresent_By: "DIGIO SMFG",
        NACH-NON-NACH: "NACH",
        NACH_Status: "Registered",
        Reason Description: "-",
        UMRN: "INDB0000000001329022",
        EMI DATE: "1/5/24",
        INSTITUTE NAME: "ISME",
        Course Name: "Business Management & Entrepreneurship",
        Stage: "Repayment",
        EMI_Amount: "4020"
      },
      {
       Sr_No: "44",
        Application_ID: "A191010019",
        Borrower_Name: "Namita Medhi",
        Contact_No.: "7838849114",
        Current_Lender: "SMFG",
        CuPresent_By: "DIGIO SMFG",
        NACH-NON-NACH: "NACH",
        NACH_Status: "Registered",
        Reason Description: "Refer Abhiram Mail",
        UMRN: "SBIN0000000032956613",
        EMI DATE: "1/5/24",
        INSTITUTE NAME: "IBS",
        Course Name: "IBS MBA",
        Stage: "Repayment",
        EMI_Amount: "3511"
      },
      {
       Sr_No: "45",
        Application_ID: "A191010083",
        Borrower_Name: "om Rustogi",
        Contact_No.: "8553370061",
        Current_Lender: "SMFG",
        CuPresent_By: "DIGIO SMFG",
        NACH-NON-NACH: "NACH",
        NACH_Status: "Registered",
        Reason Description: "-",
        UMRN: "HDFC0000000009424344",
        EMI DATE: "1/5/24",
        INSTITUTE NAME: "IBS",
        Course Name: "IBS MBA",
        Stage: "Repayment",
        EMI_Amount: "3601"
      },
      {
       Sr_No: "46",
        Application_ID: "A191012054",
        Borrower_Name: "Ramesh Bhatia",
        Contact_No.: "9891237070",
        Current_Lender: "MAS Apple 06 2023",
        CuPresent_By: "AXIS",
        NACH-NON-NACH: "NACH",
        NACH_Status: "Registered",
        Reason Description: "-",
        UMRN: "HDFC7000000010369150",
        EMI DATE: "1/5/24",
        INSTITUTE NAME: "IBS",
        Course Name: "IBS MBA",
        Stage: "Repayment",
        EMI_Amount: "3481"
      },
      {
       Sr_No: "47",
        Application_ID: "A191014001",
        Borrower_Name: "AKSHAT MADHOPURIA",
        Contact_No.: "9038506746",
        Current_Lender: "SMFG",
        CuPresent_By: "DIGIO SMFG",
        NACH-NON-NACH: "NACH",
        NACH_Status: "Registered",
        Reason Description: "-",
        UMRN: "HDFC7000000010420904",
        EMI DATE: "1/5/24",
        INSTITUTE NAME: "IBS",
        Course Name: "IBS MBA",
        Stage: "Repayment",
        EMI_Amount: "3601"
      },
      {
       Sr_No: "48",
        Application_ID: "A191014053",
        Borrower_Name: "Vishwajeet Bhosale",
        Contact_No.: "9372259303",
        Current_Lender: "SMFG",
        CuPresent_By: "DIGIO SMFG",
        NACH-NON-NACH: "NACH",
        NACH_Status: "Registered",
        Reason Description: "-",
        UMRN: "UTIB0000000009069020",
        EMI DATE: "1/5/24",
        INSTITUTE NAME: "Delphi Infotech",
        Course Name: "SAP Delphi",
        Stage: "Repayment",
        EMI_Amount: "4667"
      },
      {
       Sr_No: "49",
        Application_ID: "A191016154",
        Borrower_Name: "debdipta dasgupta",
        Contact_No.: "9903492781",
        Current_Lender: "SMFG",
        CuPresent_By: "DIGIO SMFG",
        NACH-NON-NACH: "NACH",
        NACH_Status: "Registered",
        Reason Description: "-",
        UMRN: "HDFC7000000010469903",
        EMI DATE: "1/5/24",
        INSTITUTE NAME: "TSW",
        Course Name: "IIM K - MBA",
        Stage: "Repayment",
        EMI_Amount: "4834"
      },
      {
       Sr_No: "50",
        Application_ID: "A191018035",
        Borrower_Name: "Shrinath Patil",
        Contact_No.: "7507027088",
        Current_Lender: "SMFG",
        CuPresent_By: "DIGIO SMFG",
        NACH-NON-NACH: "NACH",
        NACH_Status: "Registered",
        Reason Description: "-",
        UMRN: "HDFC7000000010542345",
        EMI DATE: "1/5/24",
        INSTITUTE NAME: "Delphi Infotech",
        Course Name: "SAP Delphi",
        Stage: "Repayment",
        EMI_Amount: "10938"
      },
      {
       Sr_No: "51",
        Application_ID: "A191019041",
        Borrower_Name: "pranav chadha",
        Contact_No.: "7838299870",
        Current_Lender: "SMFG",
        CuPresent_By: "AXIS",
        NACH-NON-NACH: "NON NACH",
        NACH_Status: "Rejected",
        Reason Description: "-",
        UMRN: "-",
        EMI DATE: "1/5/24",
        INSTITUTE NAME: "IBS",
        Course Name: "IBS MBA",
        Stage: "Repayment",
        EMI_Amount: "3480"
      },
      {
       Sr_No: "52",
        Application_ID: "A191019053",
        Borrower_Name: "Shreya Shakchi",
        Contact_No.: "8319171384",
        Current_Lender: "MAS BOOMER 08 2023",
        CuPresent_By: "AXIS",
        NACH-NON-NACH: "NACH",
        NACH_Status: "Registered",
        Reason Description: "-",
        UMRN: "UTIB0000000009100252",
        EMI DATE: "1/5/24",
        INSTITUTE NAME: "IBS",
        Course Name: "IBS MBA",
        Stage: "Repayment",
        EMI_Amount: "3601"
      },
      {
       Sr_No: "53",
        Application_ID: "A191115037",
        Borrower_Name: "Pankajkumar Varude",
        Contact_No.: "9167979654",
        Current_Lender: "SMFG",
        CuPresent_By: "DIGIO SMFG",
        NACH-NON-NACH: "NACH",
        NACH_Status: "Registered",
        Reason Description: "-",
        UMRN: "HDFC7000000010738426",
        EMI DATE: "1/5/24",
        INSTITUTE NAME: "TSW",
        Course Name: "LEAD - Advanced management program IIM-C",
        Stage: "Repayment",
        EMI_Amount: "6332"
      },
      {
       Sr_No: "54",
        Application_ID: "A191123120",
        Borrower_Name: "NikhatKhatoon ShafiAhemad",
        Contact_No.: "8446166260",
        Current_Lender: "Eduvanz Financing Pvt. Ltd.",
        CuPresent_By: "AXIS",
        NACH-NON-NACH: "NACH",
        NACH_Status: "Registered",
        Reason Description: "-",
        UMRN: "SBIN0000000041991521",
        EMI DATE: "1/5/24",
        INSTITUTE NAME: "IBS",
        Course Name: "IBS MBA",
        Stage: "Repayment",
        EMI_Amount: "3601"
      },
      {
       Sr_No: "55",
        Application_ID: "A191209014",
        Borrower_Name: "Jayanti Gour",
        Contact_No.: "9039921272",
        Current_Lender: "SMFG",
        CuPresent_By: "DIGIO SMFG",
        NACH-NON-NACH: "NACH",
        NACH_Status: "Registered",
        Reason Description: "-",
        UMRN: "ICIC7000000010739189",
        EMI DATE: "1/5/24",
        INSTITUTE NAME: "Aegis",
        Course Name: "Post Graduate Program in Data Science",
        Stage: "Repayment",
        EMI_Amount: "14796"
      },
      {
       Sr_No: "56",
        Application_ID: "A191209066",
        Borrower_Name: "MUKAT SINGH",
        Contact_No.: "9205892680",
        Current_Lender: "SMFG",
        CuPresent_By: "DIGIO SMFG",
        NACH-NON-NACH: "NACH",
        NACH_Status: "Registered",
        Reason Description: "-",
        UMRN: "SBIN0000000044990287",
        EMI DATE: "1/5/24",
        INSTITUTE NAME: "Times Pro",
        Course Name: "0",
        Stage: "Repayment",
        EMI_Amount: "8750"
      },
      {
       Sr_No: "57",
        Application_ID: "A191211090",
        Borrower_Name: "ANKIT SRIVASTAVA",
        Contact_No.: "9742069523",
        Current_Lender: "Eduvanz Financing Pvt. Ltd.",
        CuPresent_By: "AXIS",
        NACH-NON-NACH: "NACH",
        NACH_Status: "Registered",
        Reason Description: "-",
        UMRN: "SCBL0000000000970886",
        EMI DATE: "1/5/24",
        INSTITUTE NAME: "eDrishyaa",
        Course Name: "SAP Course",
        Stage: "Repayment",
        EMI_Amount: "8663"
      },
      {
       Sr_No: "58",
        Application_ID: "A191220058",
        Borrower_Name: "Chandrakant sonawane",
        Contact_No.: "9960584177",
        Current_Lender: "SMFG",
        CuPresent_By: "DIGIO SMFG",
        NACH-NON-NACH: "NACH",
        NACH_Status: "Registered",
        Reason Description: "-",
        UMRN: "UTIB0000000009627732",
        EMI DATE: "1/5/24",
        INSTITUTE NAME: "ATOS",
        Course Name: "SAP - ATOS",
        Stage: "Repayment",
        EMI_Amount: "11813"
      },
      {
       Sr_No: "59",
        Application_ID: "A191226043",
        Borrower_Name: "Kotte Kumar",
        Contact_No.: "9133411114",
        Current_Lender: "Eduvanz Financing Pvt. Ltd.",
        CuPresent_By: "AXIS",
        NACH-NON-NACH: "NACH",
        NACH_Status: "Registered",
        Reason Description: "-",
        UMRN: "KKBK0000000003781696",
        EMI DATE: "1/5/24",
        INSTITUTE NAME: "IBS",
        Course Name: "Integrated Btech",
        Stage: "Repayment",
        EMI_Amount: "3476"
      },
      {
       Sr_No: "60",
        Application_ID: "A191226093",
        Borrower_Name; "Hritabrata lahiri",
        Contact_No.: "9831238926",
        Current_Lender: "SMFG",
        CuPresent_By: "DIGIO SMFG",
        NACH-NON-NACH: "NACH",
        NACH_Status: "Registered",
        Reason Description: "-",
        UMRN: "UTIB7000000009478535",
        EMI DATE: "1/5/24",
        INSTITUTE NAME: "Times Pro",
        Course Name: "0",
        Stage: "Repayment",
        EMI_Amount: "8949"
      },
      {
       Sr_No: "61",
        Application_ID: "A191231051",
        Borrower_Name: "Atishay Nayak",
        Contact_No.: "7066543600",
        Current_Lender: "Eduvanz Financing Pvt. Ltd.",
        CuPresent_By: "AXIS",
        NACH-NON-NACH: "NACH",
        NACH_Status: "Registered",
        Reason Description: "-",
        UMRN: "UTIB7000000009538340",
        EMI DATE: "1/5/24",
        INSTITUTE NAME: "Great Lakes Institute Of Management",
        Course Name: "International Immersion Program",
        Stage: "Repayment",
        EMI_Amount: "9063"
      },
      {
       Sr_No: "62",
        Application_ID: "A200107072",
        Borrower_Name: "Rajat Sharma",
        Contact_No.: "9717824647",
        Current_Lender: "Eduvanz Financing Pvt. Ltd.",
        CuPresent_By: "AXIS",
        NACH-NON-NACH: "NACH",
        NACH_Status: "Registered",
        Reason Description: "-",
        UMRN: "HDFC7000000010988683",
        EMI DATE: "1/5/24",
        INSTITUTE NAME: "Great Learning",
        Course Name: "PGP BABI with UT Austin",
        Stage: "Repayment",
        EMI_Amount: "9562"
      },
      {
       Sr_No: "63",
        Application_ID: "A200111081",
        Borrower_Name: "Neeraj Singh",
        Contact_No.: "8860082523",
        Current_Lender: "Eduvanz Financing Pvt. Ltd.",
        CuPresent_By: "AXIS",
        NACH-NON-NACH: "NACH",
        NACH_Status: "Registered",
        Reason Description: "-",
        UMRN: "ICIC7000000010617014",
        EMI DATE: "1/5/24",
        INSTITUTE NAME: "IBS",
        Course Name: "ICFAI - BBA-LL.B(Hons) / BA-LL.B(Hons.)",
        Stage: "Repayment",
        EMI_Amount: "1626"
      },
      {
       Sr_No: "64",
        Application_ID: "A200113074",
        Borrower_Name: "Priya Shenoy",
        Contact_No.: "9987324986",
        Current_Lender: "SMFG",
        CuPresent_By: "DIGIO SMFG",
        NACH-NON-NACH: "NACH",
        NACH_Status: "Registered",
        Reason Description: "-",
        UMRN: "CNRB0000000007546805",
        EMI DATE: "1/5/24",
        INSTITUTE NAME: "ATOS",
        Course Name: "SAP - ATOS",
        Stage: "Repayment",
        EMI_Amount: "11667"
      },
      {
       Sr_No: "65",
        Application_ID: "A200114081",
        Borrower_Name: "Prerna Roy",
        Contact_No.: "8087032910",
        Current_Lender: "SMFG",
        CuPresent_By: "DIGIO SMFG",
        NACH-NON-NACH: "NACH",
        NACH_Status: "Registered",
        Reason Description: "-",
        UMRN: "HDFC7000000011349427",
        EMI DATE: "1/5/24",
        INSTITUTE NAME: "Delphi Infotech",
        Course Name: "SAP Delphi",
        Stage: "Repayment",
        EMI_Amount: "8752"
      },
      {
       Sr_No: "66",
        Application_ID: "A200121157",
        Borrower_Name: "Snehal Das",
        Contact_No.: "7978597478",
        Current_Lender: "SMFG",
        CuPresent_By: "DIGIO SMFG",
        NACH-NON-NACH: "NACH",
        NACH_Status: "Registered",
        Reason Description: "-",
        UMRN: "HDFC7000000011418258",
        EMI DATE: "1/5/24",
        INSTITUTE NAME: "IBS",
        Course Name: "IBS MBA",
        Stage: "Repayment",
        EMI_Amount: "6601"
      },
      {
       Sr_No: "67",
        Application_ID: "A200122087",
        Borrower_Name: "Bhattiprolu Kausik",
        Contact_No.: "9894777269",
        Current_Lender: "SMFG",
        CuPresent_By: "DIGIO SMFG",
        NACH-NON-NACH: "NACH",
        NACH_Status: "Registered",
        Reason Description: "-",
        UMRN: "UTIB7000000009692124",
        EMI DATE: "1/5/24",
        INSTITUTE NAME: "Insofe",
        Course Name: "PGP in Data Analytics",
        Stage: "Repayment",
        EMI_Amount: "9042"
      },
      {
       Sr_No: "68",
        Application_ID: "A200123199",
        Borrower_Name: "Sreedevi Maranganti",
        Contact_No.: "9945601077",
        Current_Lender: "SMFG",
        CuPresent_By: "DIGIO SMFG",
        NACH-NON-NACH: "NACH",
        NACH_Status: "Registered",
        Reason Description: "-",
        UMRN: "SBIN7000000044618726",
        EMI DATE: "1/5/24",
        INSTITUTE NAME: "Jaro Education",
        Course Name: "Accelerated General Management Program - IIM Ahmedabad",
        Stage: "Repayment",
        EMI_Amount: "13262"
      },
      {
       Sr_No: "69",
        Application_ID: "A2001242190",
        Borrower_Name: "Varadaraju Ramakrishna",
        Contact_No.: "9448411185",
        Current_Lender: "SMFG",
        CuPresent_By: "DIGIO SMFG",
        NACH-NON-NACH: "NACH",
        NACH_Status: "Registered",
        Reason Description: "-",
        UMRN: "SBIN0000000044579655",
        EMI DATE: "1/5/24",
        INSTITUTE NAME: "eDrishyaa",
        Course Name: "SAP Course",
        Stage: "Repayment",
        EMI_Amount: "11579"
      },
      {
       Sr_No: "70",
        Application_ID: "A200125992",
        Borrower_Name: "Utkarsh Upendra",
        Contact_No.: "8763700646",
        Current_Lender: "Eduvanz Financing Pvt. Ltd.",
        CuPresent_By: "AXIS",
        NACH-NON-NACH: "NACH",
        NACH_Status: "Registered",
        Reason Description: "-",
        UMRN: "KKBK7000000003852015",
        EMI DATE: "1/5/24",
        INSTITUTE NAME: "IBS",
        Course Name: "IBS MBA",
        Stage: "Repayment",
        EMI_Amount: "3571"
      },
      {
       Sr_No: "71",
        Application_ID: "A200127370",
        Borrower_Name: "Nidhi Ahuja",
        Contact_No.: "9899020953",
        Current_Lender: "SMFG",
        CuPresent_By: "DIGIO SMFG",
        NACH-NON-NACH: "NACH",
        NACH_Status: "Registered",
        Reason Description: "-",
        UMRN: "HDFC0000000011600671",
        EMI DATE: "1/5/24",
        INSTITUTE NAME: "Jaro Education",
        Course Name: "Accelerated General Management Program - IIM Ahmedabad",
        Stage: "Repayment",
        EMI_Amount: "17523"
      },
      {
       Sr_No: "72",
        Application_ID: "A200128183",
        Borrower_Name: "Anup Murali",
        Contact_No.: "8608980925",
        Current_Lender: "SMFG",
        CuPresent_By: "DIGIO SMFG",
        NACH-NON-NACH: "NACH",
        NACH_Status: "Registered",
        Reason Description: "-",
        UMRN: "HDFC7000000011512378",
        EMI DATE: "1/5/24",
        INSTITUTE NAME: "Great Learning",
        Course Name: "PGP Data Science & Business Analytics - Classroom with UT Austin",
        Stage: "Repayment",
        EMI_Amount: "10550"
      },
      {
       Sr_No: "73",
        Application_ID: "A200128222",
        Borrower_Name: "Padamraj Chopra",
        Contact_No.: "9820538379",
        Current_Lender: "SMFG",
        CuPresent_By: "DIGIO SMFG",
        NACH-NON-NACH: "NACH",
        NACH_Status: "Registered",
        Reason Description: "-",
        UMRN: "BKID0000000009018873",
        EMI DATE: "1/5/24",
        INSTITUTE NAME: "IBS",
        Course Name: "IBS MBA",
        Stage: "Repayment",
        EMI_Amount: "8452"
      },
      {
       Sr_No: "74",
        Application_ID: "A200206057",
        Borrower_Name: "Shinu Sinha",
        Contact_No.: "9335206351",
        Current_Lender: "SMFG",
        CuPresent_By: "DIGIO SMFG",
        NACH-NON-NACH: "NACH",
        NACH_Status: "Registered",
        Reason Description: "-",
        UMRN: "UBIN0000000005157784",
        EMI DATE: "1/5/24",
        INSTITUTE NAME: "IBS",
        Course Name: "IBS MBA",
        Stage: "Repayment",
        EMI_Amount: "3601"
      },
      {
       Sr_No: "75",
        Application_ID: "A200206119",
        Borrower_Name: "Debdipta Dasgupta",
        Contact_No.: "9903492781",
        Current_Lender: "SMFG",
        CuPresent_By: "DIGIO SMFG",
        NACH-NON-NACH: "NACH",
        NACH_Status: "Registered",
        Reason Description: "-",
        UMRN: "HDFC7000000011595114",
        EMI DATE: "1/5/24",
        INSTITUTE NAME: "TSW",
        Course Name: "IIM K - MBA",
        Stage: "Repayment",
        EMI_Amount: "4834"
      },]